import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const name='browser'+Date.now(),password='LocalSandbox123!';
const response=await fetch('http://localhost:7000/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:name,email:name+'@example.test',password})});assert.equal(response.status,201);
const browser=await chromium.launch();
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 await page.goto('http://localhost:5173');
 await page.getByRole('button',{name:'Open profile'}).click();
 await page.getByLabel('Email',{exact:true}).fill(name+'@example.test');
 await page.getByLabel('Password',{exact:true}).fill(password);
 await page.getByRole('dialog').getByRole('button',{name:'Sign in',exact:true}).click();
 await page.getByText(name,{exact:true}).waitFor();
 await page.getByRole('button',{name:'Close dialog'}).click();
 await page.getByRole('button',{name:'Deposit',exact:true}).click();
 await page.getByLabel('Amount (RWF)').fill('10000.00');
 await page.getByRole('dialog').getByRole('button',{name:'Deposit',exact:true}).click();
 await page.getByText('Deposit: COMPLETED',{exact:true}).waitFor();
 await page.getByRole('button',{name:'withdrawals',exact:true}).click();
 await page.getByLabel('Amount (RWF)').fill('50.00');
 await page.getByRole('button',{name:'Request withdrawal',exact:true}).click();
 await page.getByText('Withdrawal reserved: PENDING',{exact:true}).waitFor();
 await page.getByRole('button',{name:'transactions',exact:true}).click();
 await page.getByText(/10000.*RWF · DEPOSIT/).waitFor();
 await page.getByRole('button',{name:'Close dialog'}).click();
 await page.getByRole('button',{name:'View round history'}).click();
 const history=page.locator('.history-grid button').first();await history.waitFor();await history.click();
 await page.getByRole('button',{name:'Verify seed and result'}).click();
 await page.getByText('Seed commitment and crash result verified.',{exact:true}).waitFor();
 await page.screenshot({path:'test-results/live-fairness.png'});
 await page.getByRole('button',{name:'Close dialog'}).click();
 assert.match(await page.locator('.wallet strong').innerText(),/9,950/);
 await page.screenshot({path:'test-results/live-game.png',fullPage:true});
 console.log('PASS: real browser login, deposit, pending withdrawal, ledger, balance, round history and fairness verification');
}finally{await browser.close()}
