const fs=require('fs');const p='tests/backend.spec.ts';let s=fs.readFileSync(p,'utf8').replace(/\r\n/g,'\n');
s=s.replace('  let balance = "25000.25";','  let balance = "25000.25";\n  let savedBet: Record<string,unknown> | undefined;');
s=s.replace('const current = { id: 102, round_number: 42, status: "BETTING_OPEN" };','const current = { id: 102, round_number: 42, status: "BETTING_OPEN", betting_closes_at: new Date(Date.now()+60000).toISOString() };');
s=s.replace('return route.fulfill({ json: current });',`return route.fulfill({json:{running:null,upcoming:current,server_time:new Date().toISOString()}});
    if(path==="/api/game/rounds")return route.fulfill({json:[]});
    if(path==="/api/limits")return route.fulfill({json:{MinBet:"50",MaxBet:"1000000",MaxPayout:"100000000"}});
    if(path==="/api/deposits")return route.fulfill({json:[]});
    if(path==="/api/bets" && req.method()==="GET")return route.fulfill({json:savedBet?[savedBet]:[]});`);
s=s.replace('      balance = "24000.25";','      balance = "24000.25";\n      savedBet={id:501,round_id:102,round_number:42,round_status:"BETTING_OPEN",user_id:7,bet_number:1,amount:"1000",status:"ACTIVE",payout:"0"};');
s=s.replaceAll('/api/bets/501"','/api/bets/501/cashout"').replace('      balance = "25501.75";','      balance = "25501.75";\n      savedBet={...savedBet,status:"CASHED_OUT",payout:"1501.50",cashout_multiplier:"1.50"};');
s=s.replace('/Bet placed/','/Cancel bet/').replace('  ).toBeDisabled();\n  await expect(page.locator(".wallet strong")).toHaveText("24,000.25 RWF");','  ).toBeEnabled();\n  await expect(page.locator(".wallet strong")).toHaveText("24,000.25 RWF");');
s=s.replace('r.path === "/api/bets")','r.path === "/api/bets" && r.body)').replace('"Deposits and withdrawals are not implemented"','"SANDBOX deposits credit your local test wallet"');
s=s.replace('test("uncertain mutation is locked and survives page reload"','test("uncertain mutation is reconciled from persisted history"').replaceAll('{ name: /Unconfirmed/ }','{ name: /Bet for #42/ }');
const start=s.indexOf('test("uncertain mutation');const end=s.indexOf('test("expired session',start);s=s.slice(0,start)+s.slice(start,end).replaceAll(').toBeDisabled();',').toBeEnabled();')+s.slice(end);
fs.writeFileSync(p,s);
